### ISSUE TITLE
Can't login - getting 403 error in demo project

### ISSUE THREAD

**Issue by cdoerflinger** [SimpleDAM/SimpleDAM#1]
Trying to open https://simpledam.damnews.org/docs/ I receive a 403 Forbidden message even though it was described that for the doc there is no login needed.

```
Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by SimpleDAM** [comment]
Thanks for flagging this up.  This issue should now be fixed.
